<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rkt</string>
	</array>
	<key>name</key>
	<string>Racket</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[^\\](\"[^\"]*\")</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((define)\s+([a-zA-Z0-9_\-?\+^]+)\s*</string>
			<key>name</key>
			<string>meta.variable.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((define)\s+\(([a-zA-Z0-9_\-?\+^]+)\s*</string>
			<key>name</key>
			<string>meta.function.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\((struct)\s+([a-zA-Z0-9_\-?\+^]+)\s+</string>
			<key>name</key>
			<string>meta.struct.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\s\(](if|lambda|cond|define|type-case|let|letrec|let!|\#lang|require|test|else|first|rest|define-type|define-type-alias|define-struct|not|local|error|lang)[\s\)]</string>
			<key>name</key>
			<string>meta.keywords.source.racket</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\s\(](true|false|empty|null)[\s\)]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\s\(](#t|#f)[\s\)]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.source.racket</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#\\[a-zA-Z0-9_\-?\+\.\!\"]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0|([1-9][0-9_]*))\b</string>
			<key>name</key>
			<string>constant.numeric.integer.source.racket</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.documentation.source.racket</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#\|</string>
			<key>end</key>
			<string>\|#</string>
			<key>name</key>
			<string>comment.block.source.racket</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.racket</string>
	<key>uuid</key>
	<string>afda310a-1b2e-4b97-a0f7-13819a0ee21f</string>
</dict>
</plist>
